if [ -f ~/.bashrc.default ]; then . ~/.bashrc.default; fi
if [ -f ~/.bashrc.work ]; then . ~/.bashrc.work; fi

# common variables
export MYBASHRC='$HOME/.dotfiles/bash/bashrc'
export MYVIMRC='$HOME/.dotfiles/vim/vimrc'

# vim
set -o vi
export EDITOR='vim'
export VISUAL='vim'
export TERM="xterm-256color"
alias tmux="TERM=screen-256color-bce tmux"

# git
alias clone='~/src/github.com/trevorlangston/clone/clone.sh'
alias ggraph='git log --graph --abbrev-commit --decorate --date=relative --all'
alias glog='git log --pretty="%h - %s"'

# prompt
# export PS1="\n\[\e[36m\]\w\[\e[m\] > "

# tmux
alias tm='~/.dotfiles/bin/tm.sh'

# useful stuff
alias ll='ls -lahG'
alias updatedb='sudo /usr/libexec/locate.updatedb' # for locate command
usingport() {
    lsof -n -i4TCP:"$1" | grep LISTEN
}
