if [ -f ~/.bashrc.default ]; then . ~/.bashrc.default; fi
if [ -f ~/.bashrc.work ]; then . ~/.bashrc.work; fi

# common variables
export MYBASHRC='$HOME/.dotfiles/bash/bashrc'
export MYVIMRC='$HOME/.dotfiles/vim/vimrc'

# vim
set -o vi
export EDITOR='vim'
export VISUAL='vim'
export TERM="alacritty"

# git
alias clone='~/src/github.com/trevorlangston/clone/clone.sh'
alias ggraph='git log --graph --abbrev-commit --decorate --date=relative --all'
alias glog='git log --pretty="%h - %s"'

# tmux
alias tm='$HOME/.dotfiles/bin/tm.sh'

# emacs
alias emacs='emacs26 &> /dev/null &'

# useful stuff
alias ll='ls -lahG'
alias updatedb='sudo /usr/libexec/locate.updatedb'
usingport() {
    lsof -n -i4TCP:"$1" | grep LISTEN
}

# alias what I can't remember
alias settings="env XDG_CURRENT_DESKTOP=GNOME gnome-control-center"
alias wifi=nmtui
alias sleep="systemctl suspend"

eval `dircolors $HOME/.dir_colors/dircolors`
